// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Address struct {
	Number        string    `json:"number"`
	Route         string    `json:"route"`
	OptionalRoute *string   `json:"optionalRoute,omitempty"`
	City          string    `json:"city"`
	ZipCode       string    `json:"zipCode"`
	Country       string    `json:"country"`
	Coordinates   []float64 `json:"coordinates"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	User         *User    `json:"user"`
	Token        string   `json:"token"`
	RefreshToken string   `json:"refreshToken"`
	Permissions  []string `json:"permissions"`
	Roles        []string `json:"roles"`
}

type Mutation struct {
}

type NewAddressInput struct {
	Number        int32     `json:"number"`
	Route         string    `json:"route"`
	OptionalRoute *string   `json:"optionalRoute,omitempty"`
	City          string    `json:"city"`
	ZipCode       string    `json:"zipCode"`
	Country       string    `json:"country"`
	Coordinates   []float64 `json:"coordinates"`
}

type NewPermissionOverrideInput struct {
	UserID       uint `json:"userID"`
	PermissionID uint `json:"permissionID"`
	IsGranted    bool `json:"isGranted"`
}

type NewUserInput struct {
	Email       string               `json:"email"`
	Password    *string              `json:"password,omitempty"`
	UserProfile *NewUserProfileInput `json:"userProfile"`
}

type NewUserProfileInput struct {
	FirstName string           `json:"firstName"`
	LastName  *string          `json:"lastName,omitempty"`
	Avatar    *graphql.Upload  `json:"avatar,omitempty"`
	Phone     *string          `json:"phone,omitempty"`
	Address   *NewAddressInput `json:"address,omitempty"`
}

type PageInfo struct {
	StartCursor uint `json:"startCursor"`
	EndCursor   uint `json:"endCursor"`
	HasNextPage bool `json:"hasNextPage"`
}

type Permission struct {
	ID           uint      `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	Name         string    `json:"name"`
	ReadableName *string   `json:"readableName,omitempty"`
	Description  *string   `json:"description,omitempty"`
	Category     *string   `json:"category,omitempty"`
}

type Query struct {
}

type SortInput struct {
	Field string `json:"field"`
	Order string `json:"order"`
}

type User struct {
	ID          uint         `json:"id"`
	CreatedAt   time.Time    `json:"createdAt"`
	Email       string       `json:"email"`
	UserProfile *UserProfile `json:"userProfile,omitempty"`
	Permissions []string     `json:"permissions"`
	Roles       []string     `json:"roles"`
}

type UserProfile struct {
	ID         uint      `json:"id"`
	CreatedAt  time.Time `json:"createdAt"`
	AvatarName *string   `json:"avatarName,omitempty"`
	FirstName  string    `json:"firstName"`
	LastName   *string   `json:"lastName,omitempty"`
	Phone      *string   `json:"phone,omitempty"`
	AddressID  *uint     `json:"addressID,omitempty"`
	Address    *Address  `json:"address,omitempty"`
}
