package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"katalyx.fr/katabasegql/graph"
	"katalyx.fr/katabasegql/graph/model"
	"katalyx.fr/katabasegql/internal/authentication"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResult, error) {
	// Extract user agent and IP address from operation context
	userAgent := ""
	ipAddress := ""

	if oc := graphql.GetOperationContext(ctx); oc != nil {
		if oc.Headers != nil {
			userAgent = oc.Headers.Get("User-Agent")
		}
		if oc.Variables != nil {
			if ip, ok := oc.Variables["clientIP"].(string); ok {
				ipAddress = ip
			}
		}
	}

	dbUser, token, refreshToken, dbPermissions, err := r.AuthenticationService.Login(input, userAgent, ipAddress)

	if err != nil {
		return nil, err
	}

	var permissions []string
	var roles []string

	for _, permission := range dbPermissions {
		permissions = append(permissions, permission.Name)
	}

	for _, role := range dbUser.Roles {
		roles = append(roles, role.Name)
	}

	return &model.LoginResult{
		User:         dbUser.ToModel(),
		Token:        token,
		RefreshToken: refreshToken,
		Permissions:  permissions,
		Roles:        roles,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.LoginResult, error) {
	// Extract user agent and IP address from operation context
	userAgent := ""
	ipAddress := ""

	if oc := graphql.GetOperationContext(ctx); oc != nil {
		if oc.Headers != nil {
			userAgent = oc.Headers.Get("User-Agent")
		}
		if oc.Variables != nil {
			if ip, ok := oc.Variables["clientIP"].(string); ok {
				ipAddress = ip
			}
		}
	}

	dbUser, token, newRefreshToken, dbPermissions, err := r.AuthenticationService.RefreshAccessToken(refreshToken, userAgent, ipAddress)

	if err != nil {
		return nil, err
	}

	var permissions []string
	var roles []string

	for _, permission := range dbPermissions {
		permissions = append(permissions, permission.Name)
	}

	for _, role := range dbUser.Roles {
		roles = append(roles, role.Name)
	}

	return &model.LoginResult{
		User:         dbUser.ToModel(),
		Token:        token,
		RefreshToken: newRefreshToken,
		Permissions:  permissions,
		Roles:        roles,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUserInput) (*model.User, error) {
	dbUser, err := r.AuthenticationService.CreateUser(input)

	if err != nil {
		return nil, err
	}

	return dbUser.ToModel(), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uint, input map[string]any) (*model.User, error) {
	loggedUser := authentication.ForContext(ctx)

	dbUser, err := r.AuthenticationService.UpdateUser(loggedUser, id, input)

	if err != nil {
		return nil, err
	}

	if dbUser == nil {
		return nil, nil
	}

	return dbUser.ToModel(), nil
}

// UpdatePermissionOverride is the resolver for the updatePermissionOverride field.
func (r *mutationResolver) UpdatePermissionOverride(ctx context.Context, input model.NewPermissionOverrideInput) (bool, error) {
	_, err := r.AuthenticationService.UpdatePermissionOverride(input)

	if err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	loggedUser := authentication.ForContext(ctx)

	if loggedUser == nil {
		return nil, nil
	}

	return loggedUser.ToModel(), nil
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context) ([]*model.Permission, error) {
	dbPermissions, err := r.AuthenticationService.GetAllPermissions()

	if err != nil {
		return nil, err
	}

	var permissions []*model.Permission

	for _, dbPermission := range dbPermissions {
		permissions = append(permissions, dbPermission.ToModel())
	}

	return permissions, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
