package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"katalyx.fr/katabasegql/graph"
	"katalyx.fr/katabasegql/graph/model"
	"katalyx.fr/katabasegql/pkg/database/dbmodel"
)

// UserProfile is the resolver for the userProfile field.
func (r *userResolver) UserProfile(ctx context.Context, obj *model.User) (*model.UserProfile, error) {
	dbUser, err := r.UsersService.Get(obj.ID, &dbmodel.UserFieldsToInclude{UserProfile: true})

	if err != nil {
		return nil, err
	}

	if dbUser == nil {
		return nil, nil
	}

	return dbUser.UserProfile.ToModel(), nil
}

// Address is the resolver for the address field.
func (r *userProfileResolver) Address(ctx context.Context, obj *model.UserProfile) (*model.Address, error) {
	if obj.AddressID == nil {
		return nil, nil
	}

	dbAddress, err := r.MapsService.Get(*obj.AddressID)

	if err != nil {
		return nil, err
	}

	if dbAddress == nil {
		return nil, nil
	}

	return dbAddress.ToModel(), nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

// UserProfile returns graph.UserProfileResolver implementation.
func (r *Resolver) UserProfile() graph.UserProfileResolver { return &userProfileResolver{r} }

type userResolver struct{ *Resolver }
type userProfileResolver struct{ *Resolver }
